/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SQLBuilderCtrl;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author cesar
 */
public class DetailRelationshipGUI extends javax.swing.JDialog {

    SQLBuilderCtrl presenter;

    /**
     * Creates new form DetailRelationshipGUI
     */
    public DetailRelationshipGUI(java.awt.Frame parent, boolean modal, SQLBuilderCtrl presenter) {
        super(parent, modal);
        initComponents();
        this.presenter = presenter;
    }

    public JButton getSaveDetail() {
        return saveDetail;
    }

    public JList getListFieldSource() {
        return listFieldSource;
    }

    public JList getListFieldDestination() {
        return listFieldDestination;
    }

    public JTable getTableRelationship() {
        return tableRelationship;
    }

    public JScrollPane getScrollTableRelationship() {
        return scrollTableRelationship;
    }

    public JScrollPane getScrollFieldsDestination() {
        return scrollFieldsDestination;
    }

    public JScrollPane getScrollFieldsSource() {
        return scrollFieldsSource;
    }

    public JLabel getStatus() {
        return status;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollFieldsSource = new javax.swing.JScrollPane();
        listFieldSource = new javax.swing.JList();
        scrollTableRelationship = new javax.swing.JScrollPane();
        tableRelationship = new javax.swing.JTable();
        scrollFieldsDestination = new javax.swing.JScrollPane();
        listFieldDestination = new javax.swing.JList();
        saveDetail = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("language/Bundle_pt_BR"); // NOI18N
        setTitle(bundle.getString("DetailRelationshipGUI.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        scrollFieldsSource.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DetailRelationshipGUI.scrollFieldsSource.border.title"))); // NOI18N

        listFieldSource.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollFieldsSource.setViewportView(listFieldSource);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollFieldsSource, gridBagConstraints);

        scrollTableRelationship.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DetailRelationshipGUI.scrollTableRelationship.border.title"))); // NOI18N

        tableRelationship.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origem", "Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRelationship.getTableHeader().setReorderingAllowed(false);
        scrollTableRelationship.setViewportView(tableRelationship);
        if (tableRelationship.getColumnModel().getColumnCount() > 0) {
            tableRelationship.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("DetailRelationshipGUI.tableRelationship.columnModel.title0")); // NOI18N
            tableRelationship.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("DetailRelationshipGUI.tableRelationship.columnModel.title1")); // NOI18N
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollTableRelationship, gridBagConstraints);

        scrollFieldsDestination.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DetailRelationshipGUI.scrollFieldsDestination.border.title"))); // NOI18N

        listFieldDestination.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollFieldsDestination.setViewportView(listFieldDestination);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollFieldsDestination, gridBagConstraints);

        saveDetail.setText(bundle.getString("DetailRelationshipGUI.saveDetail.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(saveDetail, gridBagConstraints);

        status.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        status.setForeground(java.awt.Color.blue);
        status.setText(bundle.getString("DetailRelationshipGUI.status.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(status, gridBagConstraints);

        setSize(new java.awt.Dimension(799, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailRelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailRelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailRelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailRelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailRelationshipGUI dialog = new DetailRelationshipGUI(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList listFieldDestination;
    private javax.swing.JList listFieldSource;
    private javax.swing.JButton saveDetail;
    private javax.swing.JScrollPane scrollFieldsDestination;
    private javax.swing.JScrollPane scrollFieldsSource;
    private javax.swing.JScrollPane scrollTableRelationship;
    private javax.swing.JLabel status;
    private javax.swing.JTable tableRelationship;
    // End of variables declaration//GEN-END:variables
}
