/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author cesar
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI(ResourceBundle bundle) {
        this.bundle = bundle;
        initComponents();
        setSize(800, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        buttonCreateTask = new javax.swing.JButton();
        buttonSQLBuilder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonPtBr = new javax.swing.JButton();
        buttonEn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(desktopPane);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonCreateTask.setText(bundle.getString("MainGUI.buttonCreateTask.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(buttonCreateTask, gridBagConstraints);

        buttonSQLBuilder.setText(bundle.getString("MainGUI.buttonSQLBuilder.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(buttonSQLBuilder, gridBagConstraints);

        buttonPtBr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/language/pt-br.png"))); // NOI18N
        buttonPtBr.setText(bundle.getString("MainGUI.buttonPtBr.text")); // NOI18N
        buttonPtBr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPtBrActionPerformed(evt);
            }
        });
        jPanel3.add(buttonPtBr);

        buttonEn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/language/en.png"))); // NOI18N
        buttonEn.setText(bundle.getString("MainGUI.buttonEn.text")); // NOI18N
        jPanel3.add(buttonEn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jPanel3, gridBagConstraints);

        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        log.setEditable(false);
        log.setColumns(20);
        log.setRows(5);
        log.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("MainGUI.log.border.title"))); // NOI18N
        jScrollPane2.setViewportView(log);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPtBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPtBrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPtBrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI(java.util.ResourceBundle.getBundle("language/Bundle_pt_BR")).setVisible(true);
            }
        });
    }

    public JButton getButtonCreateTask() {
        return buttonCreateTask;
    }
    
    public JButton getButtonSQLBuilder() {
        return buttonSQLBuilder;
    }

    public JButton getButtonEn() {
        return buttonEn;
    }

    public JButton getButtonPtBr() {
        return buttonPtBr;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public ResourceBundle getBundle() {
        return bundle;
    }

    public JList getList() {
        return list;
    }

    public JTextArea getLog() {
        return log;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateTask;
    private javax.swing.JButton buttonEn;
    private javax.swing.JButton buttonPtBr;
    private javax.swing.JButton buttonSQLBuilder;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList list;
    private javax.swing.JTextArea log;
    java.util.ResourceBundle bundle;
    // End of variables declaration//GEN-END:variables
}
